services:
 frontend_siscol:
   build:
     context: .
     dockerfile: Dockerfile
   image: frontend-sicopesc
   container_name: frontend-sicopesc
   ports:
     - "3000:3000"
   volumes:
     - ./:/app
     - /app/node_modules
   environment:
     - CHOKIDAR_USEPOLLING=true
   stdin_open: true
   tty: true
